config/routes.rb
Accio::Application.routes.draw do

  mount Chatter::Engine, :at => '/chat'

  resources :user, :only => [:update]
  match '/notification' => 'user#notifications', :as => "notifications"
  match '/deactivate' => 'notification#deactivate'

  root :to => "home#index"
  match '/user' => 'user#index', :as => "user"
  match '/search' => "application#search", :as => "search"
  get 'home/get_users'
  get 'home/user_data'
  get 'home/request_callback'
  get 'home/help_me'
  post 'home/process_tweet'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @services = Service.all
    if current_user
      redirect_to redirect_user and return
    end
  end

  def get_users
    service=Service.find_by_id(params[:service_id])
    users = service.users.active
    @hash = Gmaps4rails.build_markers(users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow "<div class='infobox_details'><IMG BORDER='0' ALIGN='Left' SRC='https://www.google.co.in/logos/doodles/2015/nellie-blys-151st-birthday-4862371034038272-res.png' style='height:80px;width:80px'><b>#{user.name}</b><br/>#{user.phone}<br/>#{user.mobile}<br/><a href='#' onclick='showMore(#{user.id})'>Show More...</a></div>"
    end
    render :json => @hash.to_json
  end

  def user_data
    user = User.find(params[:user_id])
    render :text => user.details
  end

  def request_callback
      Notification.create!({
      user_id: params[:user_id],
      service_id: params[:service_id],
      requestor_name: params[:requestor_name],
      requestor_phone: params[:requestor_phone],
      requestor_message: params[:requestor_message]
      })
      user = User.find_by_id(params[:user_id])
      service = Service.find_by_id(params[:service_id])
      NotificationMailer.notify(user.email,"Hey, #{params[:requestor_name]} is waiting for you !!!

More Details:
      Name: #{params[:requestor_name]}
      Phone: #{params[:requestor_phone]}
      Service: #{service.name}
      Message: #{params[:requestor_message]}

With Regards,
Accio Team.")
      render :text => "True"
  end

  def help_me
    lat = params[:lat]
    lng=params[:lng]
    service_id=params[:service_id]
    requestor_name = params[:requestor_name],
    requestor_phone = params[:requestor_phone],
    requestor_message = params[:requestor_message]
    service = Service.find_by_id(params[:service_id])
    users_in_range = User.active.where("latitude between '#{lat.to_f-0.05}' and '#{lat.to_f+0.05}' and longitude between '#{lng.to_f-0.05}' and '#{lng.to_f+0.05}'" ).select{|u| u.services.include?(service)}
    nearest_users = users_in_range.sort_by{|user| user.calc_distance(lat,lng)}[0..3]
    group_id=`uuidgen`
    nearest_users.each do |user|
      Notification.create!({
      user_id: user.id,
      service_id: service_id,
      requestor_name: requestor_name,
      requestor_phone: requestor_phone,
      requestor_message: requestor_message,
      group_id: group_id
      })
    end
    NotificationMailer.notify(nearest_users.collect(&:email),"Hey, #{params[:requestor_name]} has requested help !!!

More Details:
      Name: #{params[:requestor_name]}
      Phone: #{params[:requestor_phone]}
      Service: #{service.name}
      Message: #{params[:requestor_message]}

With Regards,
Accio Team.") if nearest_users.present?
    render json: nearest_users.map { |user| {name: user.name, mobile: user.mobile} }
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_signin.html.erb
<div id="adminLoginModal" class="modal fade"  role="dialog" aria-labelledby="Signin" aria-hidden="true" data-backdrop="static" data-keyboard="false" tabindex="-1" style="z-index:99999">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 id="form_type_text" class="text-center" style="color:dodgerblue">About Us !</h4>
      </div>
      <div class="modal-body">
        <iframe width="640" height="401" src="http://www.powtoon.com/embed/fM9IVWd1erK/" frameborder="0"></iframe>
      </div>
  </div>
  </div>
</div>

app/views/home/_background_map.html.erb
<div id="sb-site">
  <div id="map_container">
    <div id="map" style="text-align:right">
    </div>
    <div id="right_menu_button" class="float-right glyphicon glyphicon-circle-arrow-left" style="font-size:xx-large; position:absolute;right:2vw;top:90vh" onclick="toggleRightMenu()" >
    </div>
   </div>
</div>

app/views/home/_help_requestor_details_form.html.erb
<%= text_field_tag 'help_requestor_name', nil, placeholder: 'Enter your name...', class: 'form-control' %><br/>
<%= text_field_tag 'help_requestor_phone', nil, placeholder: 'Enter your contact number...', class: 'form-control' %><br/>
<%= text_area_tag 'help_requestor_message',  nil, placeholder: 'Short issue description', class: 'form-control' %><br/>

app/views/home/_producer_signin.html.erb
<script>
$(document).ready(function(){
  $('#signup_form').hide();
  $('#signin_link').hide();
});
</script>
<div id="loginModal" class="modal fade"  role="dialog" aria-labelledby="Signin" aria-hidden="true" data-backdrop="static" data-keyboard="false" tabindex="-1" style="z-index:99999">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 id="form_type_text" class="text-center" style="color:dodgerblue">Signin</h4>
      </div>
      <div class="modal-body">
        <div id="signin_form" class="row">
          <%= form_for(:user, :url => session_path(:user), :html => {:class => 'form-group col-md-offset-2 col-md-8'}) do |f| %>
            <%= f.text_field :email, :class => 'form-control', :placeholder => "Enter your email" %>
            <br/>
            <%= f.password_field :password, :class => 'form-control', :placeholder => "Enter your password" %>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
            <br/>
            <%= f.submit 'Sign in', :class => 'btn btn-primary col-md-offset-4 col-md-4' %>
          <% end %>
        </div>
        <div id="signup_form" class="row">
          <%= form_for(:user, url: registration_path(:user), :html => {:class => 'form-group col-md-offset-2 col-md-8'}) do |f| %>
            <div class="field">
              <%= f.text_field :name, :class => 'form-control', :placeholder => "Enter your Full Name" %><br/>
            </div>
            <div class="field">
              <%= f.email_field :email, autofocus: true, :class => 'form-control', :placeholder => 'Enter your email' %><br/>
            </div>

            <div class="field">
              <% if @validatable %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <%= f.password_field :password, autocomplete: "off", :class => 'form-control', :placeholder => 'Enter a password' %><br/>
            </div>

            <div class="field">
              <%= f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control', :placeholder => 'Confirm your password' %>
            </div>
            <br/>
            <div class="actions">
              <%= f.submit "Sign up", :class => 'btn btn-primary col-md-offset-4 col-md-4' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Forgot your password?", new_password_path(:user), :style => 'position:absolute;left:1vw; bottom:1vh;' %>
        <%= link_to "New user? Signup", "#", :id => 'signup_link', :style => 'position:absolute;right:1vw; bottom:1vh;', :onclick => '$("#signin_form").hide(1000);$("#signup_form").show(1000);$("#form_type_text").text("Signup");$(this).hide();$("#signin_link").show()' %>
        <%= link_to "Have an account? Signin", "#", :id => "signin_link", :style => 'position:absolute;right:1vw; bottom:1vh;', :onclick => '$("#signin_form").show(1000);$("#signup_form").hide(1000);$("#form_type_text").text("Signin");$(this).hide();$("#signup_link").show()' %>
      </div>
  </div>
  </div>
</div>

app/views/home/_requestor_details_form.html.erb
<%= text_field_tag 'requestor_name', nil, placeholder: 'Enter your name...', class: 'form-control' %><br/>
<%= text_field_tag 'requestor_phone', nil, placeholder: 'Enter your contact number...', class: 'form-control' %><br/>
<%= text_area_tag 'requestor_message',  nil, placeholder: 'Short issue description', class: 'form-control' %><br/>

app/views/home/_search_page.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="form_text" class="text-center" style="color:dodgerblue">Summon me !</h4>
</div>
<div class="modal-body">	
	<div id="search_form">
		Lazy of exploring the website ? Just say what you want and we will get it for 
		you. We will provide you information of anyone exactly at your location. Try a line like : 'I need an electrician near anna nagar Chennai' OR use a pincode with `@` for better accuracy (shown as placeholder) !
		<div class="form-group" style="padding-top:3vh;">
	    <%= text_field_tag :search_text, nil,{class: "form-control", :placeholder => "Ex : I want a plumber @600048"} %>
	  </div>
	</div>
	<div id="result_set" style="display:none;">
	</div>
</div>
<div class="modal-footer">
	<div id="search_div">
	<%= button_tag('Say Accio!', onclick:"searchData();",:id=>"search_button", class: 'btn btn-primary btn-sm') %>
	</div>
	<div id="reset_div" style="display:none;">
		<%= button_tag('Reset', onclick:"toggleSearch();",:id=>"reset_button", class: 'btn btn-primary btn-sm') %>
	</div>
</div>

app/views/home/_services_modal.html.erb
<div class="modal fade col-md-offset-3 col-md-6" id="services_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Which service are you looking for ?</h4><br/>
        <div class='form-group'>
          <%= select_tag "service", options_from_collection_for_select(@services, "id", "name") , class: 'form-control center' %>
        </div>
        <button type="button" class="btn btn-primary" onclick="searchForService($('#service').val());toggleRightMenu();">Search</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_slidebar_left.html.erb
<div class="sb-slidebar sb-left sb-style-overlay sb-width-custom" style="opacity:0.8" data-sb-width="100%">
  <div class="container" style="width:100vw;height:100vh">
    <div class="row" style="color:white"><center>
      <div id="accio_logo_div">
        <%= image_tag "accio_logo.gif", style: "height: 25em;padding-top:2em", id: 'accio_logo' %>
      </div>
    </center></div>
    <div class="row images_holder" style="padding-top:15em;width:100%">
      <div class="col-md-4 col-xs-12">
        <%= image_tag "the_expert.png", style: "height:45%" %><a href="#" onclick="$('#loginModal').modal('show');"><%=image_tag "producer.png", style: "width:45%", id: "producer_image" %></a>
      </div>
      <div class="col-md-4 col-xs-12 col-md-offset-4">
        <a href="#" onclick="consumerToggle();toggleFullScreen();$('#services_modal').modal('show');"><%= image_tag "consumer.png", style: "width:45%", id: "consumer_image" %></a><%= image_tag "seeker.png", style: "height:45%" %>
      </div>
    </div>
    <div class="row" style="position:absolute;bottom:1vh;width:100%">
      <center><a href="#" onclick="$('#adminLoginModal').modal('show');"><%= image_tag "rajni.gif", style: "width:5%" %></a><br/><%= image_tag "about_us_text.png", style: "width:10%" %></center>
    </div>
  </div>
</div>

app/views/home/_slidebar_right.html.erb
<div class="sb-slidebar sb-right sb-style-overlay sb-width-thick">
  <p><center><%= image_tag "accio_logo.gif", style: "height:8em" %></center></p>
  <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          Summon me a ...
        </h4>
      </div>
      <div class="panel-body">
        <%= select_tag "service", options_from_collection_for_select(@services, "id", "name"), class: 'form-control center', onchange: 'searchForService(this.value);' %>
      </div>
    </div>

    <div class="panel-group" id="accordion">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#show_more_accordion">
            More Details...
          </a>
        </h4>
      </div>
      <div id="show_more_accordion" class="panel-collapse collapse in">
        <div id="show_more_content" class="panel-body">
          <div id="provider_details">
            <ol>
              <li>Select the help that you want to summon</li>
              <li>Move around the map, and click on any of the markers to see info</li>
              <li>Use the Show More link to get more information</li>
              <li>Check out the help me panel below</li>
              </br>
              <strong><h4>Say ACCIO !!!</h4><strong>
            </ol>
          </div>
          <div id="request_callback_div" style="display:none">
            <div class ='form-group'  >
              <strong>Help us help you...</strong><br/>
              <%= render partial: "requestor_details_form" %>
              <%= button_tag('Request Callback', onclick:"requestCallback();", class: 'btn btn-primary btn-sm btn-block') %>
            </div>
            <a href='#' class='pull-right' onclick='closeRequestCallbackForm();'>Go Back</a>
          </div>
          <div id="please_wait" class="panel-body" style="display:none">
            Please wait while we process your request !!!
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#help_me_accordion">
            Help me...
          </a>
        </h4>
      </div>
      <div id="help_me_accordion" class="panel-collapse collapse">
        <div id="help_me_content" class="panel-body">
          <strong><span class='notice'>Enable location settings in your browser to help us track your location</span></strong><br/>
          <strong><span class='notice'>Click on map to select location where help is needed</span></strong><br/>
          <%= render partial: "help_requestor_details_form" %>
          <%= button_tag('Help Me', onclick:"helpMe();", class: 'btn btn-primary btn-sm btn-block') %>
        </div>
        <div id="help_callback_div" class="panel-body" style="display:none">
            <a href='#' class='pull-right' onclick='closeHelpCallbackDiv();'>Go Back</a>
        </div>
        <div id="help_please_wait" class="panel-body" style="display:none">
            Please wait while we process your request !!!
        </div>
      </div>
    </div>
  </div>

  <div id="right_menu_close_button" class="float-left glyphicon glyphicon-circle-arrow-right" style="font-size:xx-large; position:absolute;right:2vw;top:90vh" onclick="toggleRightMenu()" >
  </div>
   <span class="glyphicon glyphicon-hand-up" style="font-size:xx-large;" aria-hidden="true" onclick="$('#searchFeatureModal').modal('show');"></span>
</div>


<div id="searchFeatureModal" class="modal fade"  role="dialog" aria-labelledby="searchFeatureModal" aria-hidden="true" data-backdrop="static" data-keyboard="false" tabindex="-1" style="z-index:99999">
  <div class="modal-dialog">
  <div class="modal-content">
    <%= render :partial => "search_page" %>
  </div>
  </div>
</div>

app/views/home/index.html.erb
<% if flash[:error].present? %> 
  <script type="text/javascript">
    alert("<%=flash[:error] %>");
  </script>
<% end %>
<%= render :partial => 'background_map' %>
<%= render :partial => 'slidebar_left' %>
<%= render :partial => 'slidebar_right' %>
<%= render :partial => 'services_modal' %>
<%= render :partial => 'producer_signin' %>
<%= render :partial => 'admin_signin' %>
<script>
var requestor_marker;
handler = Gmaps.build('Google',
  {
    markers:{
      clusterer: {
      gridSize: 20,
        maxZoom: 10
      }
    }
  });
handler.buildMap({ provider: {streetViewControl: false}, internal: {id: 'map'}}, function(){
  if(navigator.geolocation.getCurrentPosition(displayOnMap)){

  }
  else{
    var marker = handler.addMarker({lat: 20.593684, lng: 78.962880});
    handler.map.centerOn(marker);
    handler.map.serviceObject.setZoom(5);
    handler.removeMarker(marker);
    handler.fitMapToBounds();
  }
  google.maps.event.addListener(handler.getMap(), "click", function(event) {
      if($('#help_me_accordion').attr("aria-expanded")=="true") {
        if(window.requestor_marker!==undefined) {
          handler.removeMarker(window.requestor_marker);
        }
        var pos_lat = event.latLng.lat();
        var pos_lng = event.latLng.lng();
        window.requestor_marker = handler.addMarker({
          lat: pos_lat,
          lng: pos_lng,
          picture: {
            url: "assets/marker_green.png",
            width:  40,
            height: 66
          },
        });
      }
    });
});
</script>